/**
 * Public configuration example for IZA.
 *
 * Copy this file to src/00_Config.js and replace every placeholder
 * with values from your own Slack, Notion, and Google Drive environment.
 *
 * Never commit a configuration file containing real IDs or email addresses.
 */

// Google Drive and Slack
const DRIVE_FOLDER_ID = "PASTE_GOOGLE_DRIVE_FOLDER_ID";
const ALLOWED_CHANNEL = "PASTE_SLACK_CHANNEL_ID";
const IZA_ERROR_CHANNEL = "PASTE_SLACK_CHANNEL_ID";
const CONTRACTOR_OPPORTUNITIES_CHANNEL = "PASTE_SLACK_CHANNEL_ID";
const CONTRACTOR_CLAIMS_CHANNEL = "PASTE_SLACK_CHANNEL_ID";
const IZA_FINANCE_EMAIL = "finance@example.com";

// Notion API
const NOTION_VERSION = "2025-09-03";

// Notion data sources
const PROJECTS_OVERVIEW_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const PROJECT_ASSIGNMENTS_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const INVOICE_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const CLIENTS_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const TASKS_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const EXPENSES_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const ROLES_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const TEAM_DIRECTORY_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const PROJECT_BY_CONTRACTOR_DATA_SOURCE_ID = "PASTE_NOTION_DATA_SOURCE_ID";
const CONTRACTOR_INVOICE_LINE_ITEMS_DATA_SOURCE_ID =
  "PASTE_NOTION_DATA_SOURCE_ID";
const CONTRACTORS_INVOICES_DATA_SOURCE_ID =
  "PASTE_NOTION_DATA_SOURCE_ID";

// Invoice template and output folder
const CONTRACTOR_INVOICE_TEMPLATE_DOC_ID =
  "PASTE_GOOGLE_DOC_TEMPLATE_ID";
const CONTRACTOR_INVOICE_FOLDER_ID =
  "PASTE_GOOGLE_DRIVE_FOLDER_ID";